name: Build and Run on Server A

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-run:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Jetson Environment
        run: |
          just set-default

      - name: Build with XMake
        run: |
          xmake
