name: Build and Run on Server A

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Jetson Environment
        run: |
          just set-jetson

      - name: Configure XMake
        run: |
          xmake f --cuda-backend=y -v

      - name: Build with XMake
        run: |
          xmake

      - name: Run the Program
        run: |
          xmake r bm-cifar-dense-cpu -d jetson
